archive:
	tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/arm-none-eabi-g++ -std=c++17 -fno-rtti -fno-exceptions -fno-threadsafe-statics -Wnon-virtual-dtor -Werror -fno-unwind-tables -ffunction-sections -fdata-sections -fmessage-length=0 -DTF_LITE_STATIC_MEMORY -DTF_LITE_DISABLE_X86_NEON -Wsign-compare -Wdouble-promotion -Wunused-variable -Wunused-function -Wswitch -Wvla -Wall -Wextra -Wmissing-field-initializers -Wstrict-aliasing -Wno-unused-parameter  -mcpu=cortex-m4 -mfpu=auto -DTF_LITE_MCU_DEBUG_LOG -mthumb -mfloat-abi=hard -funsigned-char -mlittle-endian -fomit-frame-pointer -MD -DARMCM4_FP -DCMSIS_DEVICE_ARM_CORTEX_M_XX_HEADER_FILE=\"ARMCM4_FP.h\" -O2 -I. -Itensorflow/lite/micro/tools/make/downloads -Itensorflow/lite/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/micro/tools/make/downloads/kissfft -Itensorflow/lite/micro/tools/make/downloads/ruy -Itensorflow/lite/micro/tools/make/downloads/cmsis/Device/ARM/ARMCM4/Include -Itensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/Core/Include -Igen/cortex_m_corstone_300_cortex-m4+fp_default/genfiles/ -Igen/cortex_m_corstone_300_cortex-m4+fp_default/genfiles/ -Itensorflow/lite/micro/tools/make/downloads/kissfft -I./aed_inc -c ./aed_src/aed_model_data.cc -o ./aed_bin/aed_model_data.o
	tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/arm-none-eabi-g++ -std=c++17 -fno-rtti -fno-exceptions -fno-threadsafe-statics -Wnon-virtual-dtor -Werror -fno-unwind-tables -ffunction-sections -fdata-sections -fmessage-length=0 -DTF_LITE_STATIC_MEMORY -DTF_LITE_DISABLE_X86_NEON -Wsign-compare -Wdouble-promotion -Wunused-variable -Wunused-function -Wswitch -Wvla -Wall -Wextra -Wmissing-field-initializers -Wstrict-aliasing -Wno-unused-parameter  -mcpu=cortex-m4 -mfpu=auto -DTF_LITE_MCU_DEBUG_LOG -mthumb -mfloat-abi=hard -funsigned-char -mlittle-endian -fomit-frame-pointer -MD -DARMCM4_FP -DCMSIS_DEVICE_ARM_CORTEX_M_XX_HEADER_FILE=\"ARMCM4_FP.h\" -O2 -I. -Itensorflow/lite/micro/tools/make/downloads -Itensorflow/lite/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/micro/tools/make/downloads/kissfft -Itensorflow/lite/micro/tools/make/downloads/ruy -Itensorflow/lite/micro/tools/make/downloads/cmsis/Device/ARM/ARMCM4/Include -Itensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/Core/Include -Igen/cortex_m_corstone_300_cortex-m4+fp_default/genfiles/ -Igen/cortex_m_corstone_300_cortex-m4+fp_default/genfiles/ -Itensorflow/lite/micro/tools/make/downloads/kissfft -I./aed_inc -c ./aed_src/aed_cmodel.cc -o ./aed_bin/aed_cmodel.o
	ar rvs ./aed_lib/libcmodel.a ./aed_bin/aed_cmodel.o ./aed_bin/aed_model_data.o

archive_custom:
	tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/arm-none-eabi-g++ -std=c++17 -fno-rtti -fno-exceptions -fno-threadsafe-statics -Wnon-virtual-dtor -Werror -fno-unwind-tables -ffunction-sections -fdata-sections -fmessage-length=0 -DTF_LITE_STATIC_MEMORY -DTF_LITE_DISABLE_X86_NEON -Wsign-compare -Wdouble-promotion -Wunused-variable -Wunused-function -Wswitch -Wvla -Wall -Wextra -Wmissing-field-initializers -Wstrict-aliasing -Wno-unused-parameter  -mcpu=cortex-m4 -mfpu=auto -DTF_LITE_MCU_DEBUG_LOG -mthumb -mfloat-abi=hard -funsigned-char -mlittle-endian -fomit-frame-pointer -MD -DARMCM4_FP -DCMSIS_DEVICE_ARM_CORTEX_M_XX_HEADER_FILE=\"ARMCM4_FP.h\" -O2 -I. -Itensorflow/lite/micro/tools/make/downloads -Itensorflow/lite/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/micro/tools/make/downloads/kissfft -Itensorflow/lite/micro/tools/make/downloads/ruy -Itensorflow/lite/micro/tools/make/downloads/cmsis/Device/ARM/ARMCM4/Include -Itensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/Core/Include -Igen/cortex_m_corstone_300_cortex-m4+fp_default/genfiles/ -Igen/cortex_m_corstone_300_cortex-m4+fp_default/genfiles/ -Itensorflow/lite/micro/tools/make/downloads/kissfft -I./aed_inc -c ./aed_src/aed_custom_model_data.cc -o ./aed_bin/aed_custom_model_data.o
	tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/arm-none-eabi-g++ -std=c++17 -fno-rtti -fno-exceptions -fno-threadsafe-statics -Wnon-virtual-dtor -Werror -fno-unwind-tables -ffunction-sections -fdata-sections -fmessage-length=0 -DTF_LITE_STATIC_MEMORY -DTF_LITE_DISABLE_X86_NEON -Wsign-compare -Wdouble-promotion -Wunused-variable -Wunused-function -Wswitch -Wvla -Wall -Wextra -Wmissing-field-initializers -Wstrict-aliasing -Wno-unused-parameter  -mcpu=cortex-m4 -mfpu=auto -DTF_LITE_MCU_DEBUG_LOG -mthumb -mfloat-abi=hard -funsigned-char -mlittle-endian -fomit-frame-pointer -MD -DARMCM4_FP -DCMSIS_DEVICE_ARM_CORTEX_M_XX_HEADER_FILE=\"ARMCM4_FP.h\" -O2 -I. -Itensorflow/lite/micro/tools/make/downloads -Itensorflow/lite/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/micro/tools/make/downloads/kissfft -Itensorflow/lite/micro/tools/make/downloads/ruy -Itensorflow/lite/micro/tools/make/downloads/cmsis/Device/ARM/ARMCM4/Include -Itensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/Core/Include -Igen/cortex_m_corstone_300_cortex-m4+fp_default/genfiles/ -Igen/cortex_m_corstone_300_cortex-m4+fp_default/genfiles/ -Itensorflow/lite/micro/tools/make/downloads/kissfft -I./aed_inc -c ./aed_src/aed_custom_cmodel.cc -o ./aed_bin/aed_custom_cmodel.o
	ar rvs ./aed_lib/libcustom_cmodel.a ./aed_bin/aed_custom_cmodel.o ./aed_bin/aed_custom_model_data.o

old:
	g++ -std=c++17 -fno-rtti -fno-exceptions -fno-threadsafe-statics -Wnon-virtual-dtor -Werror -fno-unwind-tables -ffunction-sections -fdata-sections -fmessage-length=0 -DTF_LITE_STATIC_MEMORY -DTF_LITE_DISABLE_X86_NEON -Wsign-compare -Wdouble-promotion -Wunused-variable -Wunused-function -Wswitch -Wvla -Wall -Wextra -Wmissing-field-initializers -Wstrict-aliasing -Wno-unused-parameter  -DTF_LITE_USE_CTIME -Os -I. -Itensorflow/lite/micro/tools/make/downloads -Itensorflow/lite/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/micro/tools/make/downloads/kissfft -Itensorflow/lite/micro/tools/make/downloads/ruy -Igen/linux_x86_64_default/genfiles/ -Igen/linux_x86_64_default/genfiles/ -Itensorflow/lite/micro/tools/make/downloads/kissfft -I./aec_inc -c ./aed_src/aed_model_data.cc -o ./aed_bin/aed_model_data.o
	g++ -std=c++17 -fno-rtti -fno-exceptions -fno-threadsafe-statics -Wnon-virtual-dtor -Werror -fno-unwind-tables -ffunction-sections -fdata-sections -fmessage-length=0 -DTF_LITE_STATIC_MEMORY -DTF_LITE_DISABLE_X86_NEON -Wsign-compare -Wdouble-promotion -Wunused-variable -Wunused-function -Wswitch -Wvla -Wall -Wextra -Wmissing-field-initializers -Wstrict-aliasing -Wno-unused-parameter  -DTF_LITE_USE_CTIME -Os -I. -Itensorflow/lite/micro/tools/make/downloads -Itensorflow/lite/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/micro/tools/make/downloads/kissfft -Itensorflow/lite/micro/tools/make/downloads/ruy -Igen/linux_x86_64_default/genfiles/ -Igen/linux_x86_64_default/genfiles/ -Itensorflow/lite/micro/tools/make/downloads/kissfft -I./aed_inc -c ./aed_src/aed_cmodel.cc -o ./aed_bin/aed_cmodel.o
	g++ -std=c++17 -fno-rtti -fno-exceptions -fno-threadsafe-statics -Wnon-virtual-dtor -Werror -fno-unwind-tables -ffunction-sections -fdata-sections -fmessage-length=0 -DTF_LITE_STATIC_MEMORY -DTF_LITE_DISABLE_X86_NEON -Wsign-compare -Wdouble-promotion -Wunused-variable -Wunused-function -Wswitch -Wvla -Wall -Wextra -Wmissing-field-initializers -Wstrict-aliasing -Wno-unused-parameter  -DTF_LITE_USE_CTIME -I. -Itensorflow/lite/micro/tools/make/downloads -Itensorflow/lite/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/micro/tools/make/downloads/kissfft -Itensorflow/lite/micro/tools/make/downloads/ruy -Igen/linux_x86_64_default/genfiles/ -Igen/linux_x86_64_default/genfiles/ -Itensorflow/lite/micro/tools/make/downloads/kissfft -o ./aed_bin/aed.o ./aed_bin/aed_model_data.o ./aed_bin/aed_cmodel.o gen/linux_x86_64_default/lib/libtensorflow-microlite.a -Wl,--fatal-warnings -Wl,--gc-sections -lm

run:
	./aed_bin/fin.o < ./aed_src/sample_input.txt


testc:
	# gcc -I./aed_inc/ -o ./aed_bin/test.o ./aed_src/test.c ./aed_lib/libcmodel.a gen/linux_x86_64_default/lib/libtensorflow-microlite.a -Wl,--fatal-warnings -Wl,--gc-sections -lm
	gcc -I./aed_inc/ -o ./aed_bin/test.o ./aed_src/test.c -lcmodel -L./aed_lib/ -ltensorflow-microlite -L./gen/linux_x86_64_default/lib/ -Wl,--fatal-warnings -Wl,--gc-sections -lm
